global:
  postgresql:
    auth:
      username: medscan_user
      password: medscan_pass
      database: dataml

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 31336   # Dış dünyaya açılan port (30000–32767 arasında olmalı)
