images:
  airflow:
    repository: innovai/airflow-custom
    tag: v1.8
    pullPolicy: Always

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/asimerkut/airflow.git
    branch: main
    subPath: dags

env:
  - name: PYTHONPATH
    value: /opt/airflow/dags

airflow:
  config:
    core:
      test_connection: "True"

