images:
  airflow:
    repository: innovai/airflow-custom
    tag: latest

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/asimerkut/airflow.git
    branch: main
    subPath: dags

env:
  - name: PYTHONPATH
    value: /opt/airflow/dags
