images:
  airflow:
    repository: innovai/airflow-custom
    tag: latest
    pullPolicy: IfNotPresent

dags:
  persistence:
    enabled: false  # DAG'lar image'in içinde

gitSync:
    enabled: true
    repo: https://github.com/asimerkut/airflow.git
    branch: main
    subPath: dags
    syncInterval: 30
    depth: 1
    wait: 5